config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  	authenticated :user do
  		root "users#index"
  	end

  	unauthenticated do
  		root "devise/sessions#new"
  	end
  end
  
  resources :users, only: [:index, :show]
  resources :posts
  resources :pictures
  resources :comments, except: [:show, :index, :new]
  resources :friendships, except: [:index, :show]
  resources :likes, only: [:create]
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :likable, polymorphic: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def create
		@like = Like.where(user_id: params[:like][:user_id], likable_id: params[:like][:likable_id], likable_type: params[:like][:likable_type])
		if @like.blank?
			@like = Like.new(like_params)
			if @like.save
				redirect_back(fallback_location: post_path(params[:like][:likable_id]))
			else
				redirect_to root_path
			end
		else
			@like.first.destroy
			redirect_back(fallback_location: post_path(params[:like][:likable_id]))
		end
	end

	private

	def like_params
		params.require(:like).permit(:user_id, :likable_id, :liked, :likable_type)
	end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(:like, url: likes_path, html: { class: "like-form"}) do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :likable_id, value: posting.id %>
	<%= f.hidden_field :likable_type, value: "#{posting.class}" %>
	<%= f.submit "Like (#{posting.likes.count})", class: "likes" %>
<% end %>