config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  	authenticated :user do
  		root "users#index"
  	end

  	unauthenticated do
  		root "devise/sessions#new"
  	end
  end
  
  resources :users, only: [:index, :show]
  resources :posts
  resources :pictures
  resources :comments, except: [:show, :index, :new]
  resources :friendships, except: [:index, :show]
  resources :likes, only: [:create]
end

app/views/shared/_comments.html.erb
<section class="comments">
	<h2 class="comments-title">Comments:</h2>
	<% @posting.comments.each do |comment| %>
		<% unless comment.commenter.nil? %>
			<div class="comment">
				<p><%= comment.body %></p>
				<i>by <%= link_to comment.commenter.username, user_path(comment.commenter.id) %></i> <i>on <%= comment.updated_at.strftime("%m-%d-%Y at %I:%M %p") %></i>
				<% if comment.commenter.id == current_user.id %>
					<%= link_to "Edit", edit_comment_path(comment.id, commentable_id: @posting.id, commentable_type: @posting.class, edit: true), class: "right-link" %>
					<%= link_to "Delete", comment_path(comment, commentable_id: @posting.id), method: :delete, class: "right-link" %>
				<% end %>
			</div>
		<% end %>
	<% end %>
	<%= render "comments/form" %>
</section>

app/views/shared/_links.html.erb
<i>Created by <%= link_to @posting.user.username, user_path(@posting.user) %></i> <i>Created on <%= @posting.created_at.strftime("%m-%d-%Y at %I:%M %p") %></i>
<span class="right-link">Comment (<%= @posting.comments.count %>)</span>
<%= render "likes/form", posting: @posting %>