config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  	authenticated :user do
  		root "users#index"
  	end

  	unauthenticated do
  		root "devise/sessions#new"
  	end
  end
  
  resources :users, only: [:index, :show]
  resources :posts
  resources :pictures
  resources :comments, except: [:show, :index, :new]
  resources :friendships, except: [:index, :show]
  resources :likes, only: [:create]
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes, as: :likable, dependent: :destroy
	has_many :comments, as: :commentable, dependent: :destroy

	mount_uploader :picture, ::PictureUploader

	validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
	end

	def show
		if params[:edit]
			@comment = Comment.find(params[:comment_id])
		else
			@comment = Comment.new
		end
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post successfully created!"
			redirect_to @post
		else
			flash.now[:error] = "Please check your info!"
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update_attributes(post_params)
			flash[:success] = "Post successfully updated!"
			redirect_to @post
		else
			flash.now[:error] = "Please check your info!"
			render :edit
		end
	end

	def destroy
		@post.destroy
		
		flash[:success] = "Post successfully deleted!"
		redirect_back(fallback_location: posts_path)
	end

	private

	def post_params
		params.require(:post).permit(:body, :picture, :remove_picture)
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/helpers/posts_helper.rb
module PostsHelper

	def friend_ids
  	current_user.friendships.map { |f| f.friender_id } + current_user.friendings.map { |f| f.friend_id } << current_user.id
  end

	def posts
		id_list = friend_ids
		posts = Post.all.order(created_at: :desc).select { |p| id_list.include?(p.user_id) }
		posts += Picture.all.order(created_at: :desc).select { |p| id_list.include?(p.user_id) }
		posts.sort! { |a, b| b.created_at <=> a.created_at }
	end
end

app/views/posts/_form.html.erb
<div class="form-container">
	<%= form_for(@post, html: { multipart: true }) do |f| %>
		<%= f.text_area :body %>
		<% if f.object.picture? %>
			<div class="preview">
					<%= image_tag(f.object.picture.thumb) %>
					<%= f.check_box :remove_picture, class: "checkbox" %>
					<%= f.label :remove_picture, class: "checkbox-label" %>
			</div>
			<p class="or">OR</p>
		<% end %>
		<div class="attach">
			<%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png" %>
		</div>

		<%= f.submit "Submit", class: "submit" %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<section>
	<h1 class="title">Edit your post</h1>
	<%= render "form" %>
</section>

app/views/posts/index.html.erb
<section>
	<h1 class="title">Posts</h1>
	<% posts.each do |post| %>
		<div class="post">
			<%= image_tag(post.user.picture, size: "30", class: "post-index-pic") %>
			<%= link_to post.user.username, user_path(post.user), class: "post-index-name" %>
			<% if post.class == Post %>
				<p><%= link_to post.body[0..250] + "...", post_path(post), class: "post-index-text" %></p>
			<% else %>
				<%= link_to image_tag(post.picture, class: "picture"), picture_path(post) %>
			<% end %>
			<i>Created on <%= post.created_at.strftime("%m-%d-%Y at %I:%M %p") %></i>
			<%= link_to "Comment (#{post.comments.count})", path(post), class: "right-link" %>
			<%= render "likes/form", posting: post %>
		</div>
	<% end %>
</section>

app/views/posts/new.html.erb
<section>
	<h1 class="title">Create a post</h1>
	<%= render "form.html.erb" %>
</section>

app/views/posts/show.html.erb
<section>
	<p class="post-text"><%= @post.body %></p>
	<%= image_tag @post.picture, class: "post-pic" %>
	<div class="post-links">
		<%= render "shared/links" %>
	</div>
	<%= render "shared/comments" %>
</section>