config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
  	authenticated :user do
  		root "users#index"
  	end

  	unauthenticated do
  		root "devise/sessions#new"
  	end
  end
  
  resources :users, only: [:index, :show]
  resources :posts
  resources :pictures
  resources :comments, except: [:show, :index, :new]
  resources :friendships, except: [:index, :show]
  resources :likes, only: [:create]
end

app/views/layouts/_footer.html.erb
<footer>
	<p class="by">by S.Q.</p>
</footer>

app/views/layouts/_friends.html.erb
<div class="friends">
	<h3 class="friends-title">Friends</h3>
	<ul>
		<% friends(current_user).each do |friend| %>
			<a href="<%= user_path(friend) %>" title="<%= friend.username %>"><li class="friend"><%= image_tag(friend.picture, size: "29") %></li></a>
		<% end %>
	</ul>
</div>

app/views/layouts/_header.html.erb
<header>
	<%= link_to image_tag("r.png", size: "25", title: "RoRbook"), root_path, class: "logo" %>
	<nav class="nav">
		<ul>
		<% if user_signed_in? %>
			<a href="<%= users_path %>"><li>Users</li></a>
			<a href="<%= posts_path %>"><li>Posts</li></a>
			<a href="<%= user_path(current_user) %>"><li>Profile</li></a>
			<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
		<% else %>
			<a href="<%= new_user_session_path %>"><li>Sign in</li></a>
			<a href="<%= new_user_registration_path %>"><li>Sign up</li></a>
		<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_profile.html.erb
<section class="profile">
	<div class="header-im">
		<%= link_to image_tag("r.png", size: "25", title: "RoRbook"), root_path, class: "logo" %>
	</div>
	<div class="user-info">
		<%= link_to image_tag(current_user.picture, size: "50", class: "user-pic"), user_path(current_user) %>
		<h2 class="username"><%= current_user.username %></h2>
	</div>
	<div class="profile-actions">
		<%= link_to "Create a post", new_post_path, class: "profile-action" %>
		<%= link_to "Share a picture", new_picture_path, class: "profile-action" %>
		<%= link_to "Edit account", edit_user_registration_path, class: "profile-action" %>
	</div>
	<% if current_user.friendships.any? { |f| f.approve == 0 && !f.friender_id.nil?} %>
		<%= render "layouts/requests" %>
	<% end %>
	<%= render "layouts/friends" %>
</section>

app/views/layouts/_requests.html.erb
<div class="requests">
	<h3 class="request-title">Friend Requests</h3>
	<ul>
		<% current_user.friendships.each do |friendship| %>
			<% if friendship.approve == 0 && !friendship.friender_id.nil? %>
				<li class="request"><%= link_to friendship.friender.username, user_path(friendship.friender) %> wants to add you as a friend</li>
				<%= form_for(:friendship, url: friendship_path(friendship), method: :patch) do |f| %>
					<%= f.hidden_field :approve, value: 1 %>
					<%= f.submit "Accept", class: "accept" %>
				<% end %>
				<%= link_to "Decline", friendship_path(friendship), method: :delete, class: "decline" %>
			<% end %>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorBook</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag       'favicon.ico' %>
    <%= stylesheet_link_tag    'reset' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag		 'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<%= render "layouts/header" %>

    <%= render "layouts/footer" %>

    <div class="container">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      
      <% if user_signed_in? %>
        <%= render "layouts/profile" %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>